services:
  web:
    build: .
    ports:
      - "8000:8000"
    env_file: .env
    depends_on:
      - db
    volumes:
      - .:/app
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: messenger
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
  test:
    build:
      context: .
    command: ["sh", "-c", "pytest tests/ -v"]
    entrypoint: ""
    environment:
      - TESTING=1
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - POSTGRES_DB=messenger
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    env_file: .env
    depends_on:
      - db
    volumes:
      - .:/app

volumes:
  db_data:
